### ISSUE TITLE
3.0.0 release

### ISSUE THREAD

**Issue by remear** [net-ssh/net-sftp#92]
How are things looking for a 3.0.0 release?

**Comment by mfazekas** [comment]
@remear have you tried 3.0.0.beta1?

**Comment by remear** [comment]
We're in the process of testing it for our use cases.

**Comment by thbar** [comment]
I wonder just about the same, as I'm about to embark in a project which requires SFTP connectivity from Ruby ^_^.

The latest official release (2.1.2) is now almost 7 years old, so I have a bit of concerns. I wonder how compatible the gem will be with e.g. Ruby 2.7, or recent versions of JRuby.

Not asking for anything (especially as an OSS maintainer myself), but wondering: @mfazekas are there still intentions to publish a v3, or is it postponed for the time being?

Also, is 3.0.0.beta1 close (API-wise) from the previous version? Is it also usable in production despite being labelled beta?

Many thanks for any input you'll be able to provide.

**Comment by mfazekas** [comment]
I've released `3.0.0.rc1` one i have feedback i'll release final verison

**Comment by thbar** [comment]
@mfazekas thanks for your work on this! I will report with feedback very soon (I'm using `net-sftp` for a recent client projet).

**Comment by thbar** [comment]
For those interested in reviewing the changes between the previous published version (2.1.2) and `v3.0.0.rc1`, here is the link:

https://github.com/net-ssh/net-sftp/compare/v2.1.2...net-ssh:v3.0.0.rc1

**Comment by thbar** [comment]
@mfazekas with a limited testing (login, download to IO etc), things seem to be working nicely. My test suite also pass. Here is my additional feedback to improve the release:

#### Cannot set the protocol version in `Net::SFTP.start`

The new version allows one to force the SFTP version here in `Net::SFTP::Session.new`, which is a nice improvement:

https://github.com/net-ssh/net-sftp/blob/269b09722370c2e3f14396b84a096174027d95cb/lib/net/sftp/session.rb#L78

The "hello world" [here](https://github.com/net-ssh/net-sftp#synopsis-), though, uses `Net::SFTP.start` instead, and there one cannot apparently set the protocol version:

https://github.com/net-ssh/net-sftp/blob/acbd1f7d435bb8bcc89a31b91bdfb6c8943df640/lib/net/sftp.rb#L30-L32

This problem is commonly faced by new users (#66, #78).

For now my fix is to monkey-patch the library (as advised above), e.g.:

```ruby
class Net::SFTP::Session
  HIGHEST_PROTOCOL_VERSION_SUPPORTED = 3
end
```

-> it would be great to support passing the version in `Net::SFTP.start` directly, maybe with an optional extra arg.

If interested, let me know, I can provide a PR for that.

#### JRuby support

The library (before or now) won't work with JRuby out of the box. One has to patch things that way:

```ruby
if RUBY_ENGINE == 'jruby'
  Net::SSH::Transport::Algorithms::ALGORITHMS.values.each { |algs| algs.reject! { |a| a =~ /^ecd(sa|h)-sha2/ } }
  Net::SSH::KnownHosts::SUPPORTED_TYPE.reject! { |t| t =~ /^ecd(sa|h)-sha2/ }
end
```

I do not suggest to update `net-sftp` for this, but I think it would be good to document this (maybe in the readme?). If a v3 is published, the library will get more eyeballs, and some people could just leave and believe that the library doesn't work on JRuby, when there is an easy work-around!

That's it for now @mfazekas, let me know if I can help further!

**Comment by thbar** [comment]
I have requested more feedback here: https://www.reddit.com/r/ruby/comments/g8aj5m/psa_netsftp_v300rc1_is_available_for_testing/

**Comment by katafrakt** [comment]
FWIW I think JRuby fix should be automatic and included in the library. There's no reason to treat JRuby as a second-class citizen in this case.

**Comment by mfazekas** [comment]
@thbar 

1.) on passing protocol, pls submit a PR. I'd say since it's not a backward incompat change we can put to 3.0.1

2.) on jruby ideally it should be solved at net-ssh level.

**Comment by thbar** [comment]
@mfazekas I will propose a PR on both projects shortly. Thanks!

**Comment by mfazekas** [comment]
@katafrakt the situation is a bit more complex than we treat JRuby as a second class citizen or not.

That is not a proper "fix" but a workaround. If we put it here we'll face ugly issues, like if that issue gets fixed on later jruby/net-ssh side then this workaround will disable for all net-sftp users.

Supporting jruby is not trivial, for example at `net-ssh` we have jurby running on CI. It's now on allowed failure as we just don't have the resources to investigate, and fix all the errors that are coming from jruby. For example our testsuite now seems to timeout in jruby: https://travis-ci.org/github/net-ssh/net-ssh/jobs/679435326 

Since we have very limited resources we focus on getting stuff running on cruby. If CI would be running we'd look after simpler jruby issues, but we just don't have resource/expertise for more complex jruby related issues. If jruby is important to you please help 'net-ssh'.

**Comment by thbar** [comment]
@mfazekas the first part is covered in https://github.com/net-ssh/net-sftp/pull/107. I did limited bits of testing on a server for now, but will do more later!

Re JRuby: full support seems unlikely for now (CI can be a true burden), yet it is otherwise nicely working for us! If I face a trouble, I will definitely report back and create PR if possible.

"Summoning" @headius from JRuby team: what is your opinion on a PR where I'd remove `/^ecd(sa|h)-sha2/` from `Net::SSH` support for JRuby? Does it make sense? Are there plans to cover this in JRuby soon, or is it instead (as I presume) a better track to just remove them for now? Thanks for your input!

**Comment by mfazekas** [comment]
@thbar on net-ssh
One of the issue is that we've used to check for `defined?(OpenSSL::PKey::EC)` but it was removed in a refactoring:
https://github.com/net-ssh/net-ssh/pull/696/files

We've even confirmed before that jruby has that:
https://github.com/net-ssh/net-ssh/issues/695#issuecomment-524021805


What seems to happen is that jruby defines OpenSSL::PKey::EC but deoesn't fully implements it, see the bellow comment for an example that will not work on jruby:
https://github.com/net-ssh/net-ssh/issues/655#issuecomment-619610439

Sure we accept patch to address disabling related algs in `net-ssh`.

**Comment by thbar** [comment]
@mfazekas thanks for the input!

Short term, after playing a bit today with the Net::SSH test suite and implementation: it seems like removing those algorithms will break a good amount of tests for now (I thought about a design that would remove the algorithms by default, yet let the user override via options, so that later if support comes in, JRuby can be upgraded without having `Net::SSH` updated itself). I can't pursue that right now (it will take more time than I have available), but I may revisit later (with a wider JRuby support, possibly!).

So my contribution will remain at #107 only for this round.

Thanks again for your input and taking the effort to release this new version, this is much appreciated!

**Comment by thbar** [comment]
@remear Net::SFTP v3.0.0 has been released. Could you please close the issue? Thanks!

**Comment by remear** [comment]
Thanks for all the great work!
